@echo off
echo Checking for processes on port 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3000 ^| findstr LISTENING') do (
    echo Killing process %%a on port 3000...
    taskkill /F /PID %%a
)
timeout /t 2 /nobreak >nul
echo Starting Next.js dev server on port 3000...
next dev
